#!/usr/bin/env python3
"""Layer 1 deterministic gate: detect coverage regression.

Expects two JSON files produced by `coverage json`:
  - coverage-before.json  (base branch, generated by CI)
  - coverage-after.json   (PR branch, generated by CI)

If coverage-before.json is missing (first run or base has no data),
the check passes with a warning.

Exit 0 = pass, exit 2 = blocked (>2% regression).
"""
import json
import pathlib
import sys

ALLOWED_DROP = -2.0  # percentage points


def _load(path: str) -> float | None:
    p = pathlib.Path(path)
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text())
        return data["totals"]["percent_covered"]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        print(f"[WARN] Could not parse {path}: {exc}")
        return None


def main() -> None:
    before_pct = _load("coverage-before.json")
    after_pct = _load("coverage-after.json")

    if after_pct is None:
        print("[WARN] coverage-after.json missing — skipping check")
        sys.exit(0)

    if before_pct is None:
        print(f"[WARN] No baseline coverage. Current: {after_pct:.1f}%")
        sys.exit(0)

    delta = after_pct - before_pct
    print(f"Coverage: {before_pct:.1f}% -> {after_pct:.1f}% (delta: {delta:+.1f}%)")

    if delta < ALLOWED_DROP:
        print(f"[BLOCK] Coverage dropped {abs(delta):.1f}% (allowed: {abs(ALLOWED_DROP):.1f}%)")
        sys.exit(2)

    print("[PASS] coverage delta acceptable")


if __name__ == "__main__":
    main()
